/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Connection.JDBC;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Rasindu
 */
public class cashior extends javax.swing.JFrame {

    /**
     * Creates new form order
     */
    public cashior() {
        initComponents();
        
    }
    
     private float value = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        ocid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ta = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        da = new javax.swing.JLabel();
        sn = new javax.swing.JLabel();
        yb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        getm = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ta1 = new javax.swing.JLabel();
        result1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cma = new javax.swing.JTextField();
        bal = new javax.swing.JLabel();
        Cas = new javax.swing.JRadioButton();
        Crd = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        ta2 = new javax.swing.JLabel();
        result2 = new javax.swing.JLabel();
        ta3 = new javax.swing.JLabel();
        result3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "Product Id", "Cart Id", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(tab);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 700, 130));

        ocid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ocidKeyPressed(evt);
            }
        });
        jPanel1.add(ocid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 290, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 100, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cash Payment bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 160, -1));

        ta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ta.setForeground(new java.awt.Color(255, 255, 255));
        ta.setText("Balance :");
        jPanel1.add(ta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 140, 30));

        result.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));
        result.setText("0.00");
        jPanel1.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 130, 30));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cashior");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 200, 50));

        da.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        da.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 160, 30));

        sn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sn.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 160, 30));

        yb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yb.setForeground(new java.awt.Color(255, 255, 255));
        yb.setText("Your Bill Are Ready");
        jPanel1.add(yb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 200, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payment Method :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        getm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getm.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(getm, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 70, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Method :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        ta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ta1.setForeground(new java.awt.Color(255, 255, 255));
        ta1.setText("Amount :");
        jPanel1.add(ta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 140, 30));

        result1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        result1.setForeground(new java.awt.Color(255, 255, 255));
        result1.setText("0.00");
        jPanel1.add(result1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 130, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Checkout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 100, 30));

        jButton5.setBackground(new java.awt.Color(255, 0, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 50, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Balance :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, -1, -1));
        jPanel1.add(cma, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 130, -1));

        bal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 255, 255));
        bal.setText("0.00");
        jPanel1.add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, -1));

        Cas.setForeground(new java.awt.Color(255, 255, 255));
        Cas.setText("Cash");
        jPanel1.add(Cas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        Crd.setForeground(new java.awt.Color(255, 255, 255));
        Crd.setText("Card");
        jPanel1.add(Crd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("cash amount :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, -1));

        ta2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ta2.setForeground(new java.awt.Color(255, 255, 255));
        ta2.setText("Net Amount : ");
        jPanel1.add(ta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 140, 30));

        result2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        result2.setForeground(new java.awt.Color(255, 255, 255));
        result2.setText("0.00");
        jPanel1.add(result2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 130, 30));

        ta3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ta3.setForeground(new java.awt.Color(255, 255, 255));
        ta3.setText("Cash Amount :");
        jPanel1.add(ta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 140, 30));

        result3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        result3.setForeground(new java.awt.Color(255, 255, 255));
        result3.setText("0.00");
        jPanel1.add(result3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 130, 30));

        jButton6.setBackground(new java.awt.Color(255, 0, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Card Payment bill");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 160, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 60, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ord.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cusStr = ocid.getText().trim();

    try {
       

        int cusid = Integer.parseInt(cusStr);

   
        PreparedStatement pst = JDBC.connectdb().prepareStatement(
            "SELECT * FROM cart WHERE cid= ?");
        pst.setInt(1, cusid); // Use setInt for an integer parameter

        ResultSet rs = pst.executeQuery();

      
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);

       

      
        while (rs.next()) {
            
            String dbcusid = Integer.toString(rs.getInt("cid")); // Convert int to String
            String dbproid = Integer.toString(rs.getInt("pid")); // Convert int to String
            String dbcartid = Integer.toString(rs.getInt("cartid")); // Convert int to String
            String dbquantity = Integer.toString(rs.getInt("quantity")); // Convert int to String
            String dbtotal = Float.toString(rs.getFloat("total")); // Convert int to String

            String tbData[] = {dbcusid, dbproid, dbcartid, dbquantity, dbtotal};
            model.addRow(tbData);
        }

  
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sum(){
        float sum = 0;
        for (int i = 0; i < tab.getRowCount(); i++){
            sum = sum + Float.parseFloat(tab.getValueAt(i,4).toString());
        }
        result1.setText(String.valueOf("Rs." +sum ));
     
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Camount = cma.getText();
        float sum = 0;
        for (int i = 0; i < tab.getRowCount(); i++){
            sum = sum + Float.parseFloat(tab.getValueAt(i,4).toString());
        }
        float cashamount = Integer.parseInt(cma.getText());
        float tot = cashamount - sum ;
        result3.setText(Camount);
        result.setText(String.valueOf("Rs." +tot ));
        result2.setText(String.valueOf("Rs." +sum ));
        
        //get method
        String payment = Cas.getText();        
        getm.setText(payment);
        
        //end method
        SimpleDateFormat dateformat = new  SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        da.setText(dateformat.format(date));
        sn.setText(String.valueOf("RY Mobile Shop"));
        ta.setText(String.valueOf("Balance :"));
        yb.setText(String.valueOf("Your Bill Are Ready"));
        
        bill();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sum();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String Method = Cas.getText();

                if (Method.equals("cash")) {
                } else {
                                    }
        float sum = 0;
        for (int i = 0; i < tab.getRowCount(); i++){
            sum = sum + Float.parseFloat(tab.getValueAt(i,4).toString());
        float cashamount = Integer.parseInt(cma.getText());
        float tot = cashamount - sum ;
        bal.setText(String.valueOf("Rs." +tot ));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        float sum = 0;
        for (int i = 0; i < tab.getRowCount(); i++){
            sum = sum + Float.parseFloat(tab.getValueAt(i,4).toString());
        }
        result2.setText(String.valueOf("Rs." +sum ));
        
        //get method
        String payment = Cas.getText();        
        getm.setText(payment);
        
        //end method
        SimpleDateFormat dateformat = new  SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        da.setText(dateformat.format(date));
        sn.setText(String.valueOf("RY Mobile Shop"));
        ta.setText(String.valueOf("Balance :"));
        yb.setText(String.valueOf("Your Bill Are Ready"));
        CardBill();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ocidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ocidKeyPressed
        // TODO add your handling code here:
        String cusStr = ocid.getText().trim();
if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
    try {
       

        int cusid = Integer.parseInt(cusStr);

   
        PreparedStatement pst = JDBC.connectdb().prepareStatement(
            "SELECT * FROM cart WHERE cid= ?");
        pst.setInt(1, cusid); // Use setInt for an integer parameter

        ResultSet rs = pst.executeQuery();

      
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);

       

      
        while (rs.next()) {
            
            String dbcusid = Integer.toString(rs.getInt("cid")); // Convert int to String
            String dbproid = Integer.toString(rs.getInt("pid")); // Convert int to String
            String dbcartid = Integer.toString(rs.getInt("cartid")); // Convert int to String
            String dbquantity = Integer.toString(rs.getInt("quantity")); // Convert int to String
            String dbtotal = Float.toString(rs.getFloat("total")); // Convert int to String

            String tbData[] = {dbcusid, dbproid, dbcartid, dbquantity, dbtotal};
            model.addRow(tbData);
        }

  
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
    }}
    }//GEN-LAST:event_ocidKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        staff s = new staff();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashior().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cas;
    private javax.swing.JRadioButton Crd;
    private javax.swing.JLabel bal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cma;
    private javax.swing.JLabel da;
    private javax.swing.JLabel getm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ocid;
    private javax.swing.JLabel result;
    private javax.swing.JLabel result1;
    private javax.swing.JLabel result2;
    private javax.swing.JLabel result3;
    private javax.swing.JLabel sn;
    private javax.swing.JLabel ta;
    private javax.swing.JLabel ta1;
    private javax.swing.JLabel ta2;
    private javax.swing.JLabel ta3;
    private javax.swing.JTable tab;
    private javax.swing.JLabel yb;
    // End of variables declaration//GEN-END:variables

public void bill(){
    
    System.out.println("");
    System.out.println("");
    System.out.println("RY Mobile Shop");
    SimpleDateFormat dateformat = new  SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        System.out.println(dateformat.format(date));
    System.out.println("-----------------------------");
    System.out.println("");
    String payment = Cas.getText();
        getm.setText(payment);
    System.out.println("Payment Method : "+payment);
    float sum = 0;
        for (int i = 0; i < tab.getRowCount(); i++){
            sum = sum + Float.parseFloat(tab.getValueAt(i,4).toString());
        }
    System.out.println(("Net Amount : " + "Rs  " +sum ));
    float cashamount = Integer.parseInt(cma.getText());
        float tot = cashamount - sum ;
                        System.out.println("Cash amount : " + cashamount);
    System.out.println("Balance : " + tot);
    System.out.println("");
    System.out.println("------------------------------");
    System.out.println("Thank You Come Agian...");
}
public void CardBill(){
    
    System.out.println("");
    System.out.println("");
    System.out.println("RY Mobile Shop");
    SimpleDateFormat dateformat = new  SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        System.out.println(dateformat.format(date));
    System.out.println("---------------------------");
    System.out.println("");
    float sum = 0;
        for (int i = 0; i < tab.getRowCount(); i++){
            sum = sum + Float.parseFloat(tab.getValueAt(i,4).toString());
        }
    System.out.println(("Net Amount : " + "Rs  " +sum ));
    String payment = Crd.getText();
        getm.setText(payment);
    System.out.println("Payment Method : "+payment);
    System.out.println("Your Card accepted");
    System.out.println("Total amount : " + sum);
        System.out.println("");
        System.out.println("-----------------------------");
    System.out.println("Thank You Come Agian...");
    System.out.println("===============================");

}}

