/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Connection.JDBC;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rasindu
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "fname", "lname", "phone", "email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 760, 50));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 90, -1));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idKeyPressed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 350, -1));
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 210, -1));
        jPanel1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 210, -1));
        jPanel1.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 350, -1));
        jPanel1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 350, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Save");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 90, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Update");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 90, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Delete");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 90, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("EXIT");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cus.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int cusid =  Integer.parseInt(id.getText());
        String cusfname = fn.getText();
        String cuslname = ln.getText();
        String cuspn = pn.getText();
        String cusemail = em.getText();
        
        try {
            PreparedStatement pst = JDBC.connectdb().prepareStatement("INSERT INTO customer(cid, fname, lname, phone, email) VALUES (?,?,?,?,?)");
            pst.setInt(1,cusid);
            pst.setString(2,cusfname);
            pst.setString(3,cuslname);
            pst.setString(4,cuspn);
            pst.setString(5,cusemail);
            
            
            int rs = pst.executeUpdate();
            if (rs > 0) {
    JOptionPane.showMessageDialog(null, "Insert Successful.");
                id.setText("");
                fn.setText("");
                ln.setText("");
                pn.setText("");
                em.setText("");

            }else{
                System.out.println(""+"Not save");
            }
              
        }catch(Exception E){
            System.out.println(""+E);
            
            E.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int cusid =  Integer.parseInt(id.getText());
        String cusfname = fn.getText();
        String cuslname = ln.getText();
        String cuspn = pn.getText();
        String cusemail = em.getText();
        
        try {
            PreparedStatement pst = JDBC.connectdb().prepareStatement("UPDATE customer SET fname=?, lname=?, phone=?, email=? WHERE cid=?");
            pst.setString(1,cusfname);
            pst.setString(2,cuslname);
            pst.setString(3,cuspn);
            pst.setString(4,cusemail);
            pst.setInt(5,cusid);
          
            
            int rs = pst.executeUpdate();
            if (rs > 0) {
                
    JOptionPane.showMessageDialog(null, "Update Data Successfully.");
            }else{
                System.out.println(""+"Not Updated.");
            }
              
        }catch(Exception E){
            System.out.println(""+E);
            E.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String cusnic =id.getText();
        try {
            PreparedStatement pst = JDBC.connectdb().prepareStatement("DELETE from customer WHERE cid=?");
            pst.setString(1,cusnic);
            
            int rs = pst.executeUpdate();
            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Delete Data Successfully!");
            }else{
                System.out.println(""+"not save");
            }
            
        }catch (Exception e) {
            System.out.println(""+e);
        }  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cusidStr = id.getText().trim();

    try {
       

        int empid = Integer.parseInt(cusidStr);

   
        PreparedStatement pst = JDBC.connectdb().prepareStatement(
            "SELECT * FROM customer WHERE cid= ?");
        pst.setInt(1, empid); // Use setInt for an integer parameter

        ResultSet rs = pst.executeQuery();

      
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();       

      
        while (rs.next()) {
            
            String fname = rs.getString("fname");
            String lname = rs.getString("lname");
            String phone = rs.getString("phone");
            String email = rs.getString("email");
            String dbcusid = Integer.toString(rs.getInt("cid")); // Convert int to String

            String tbData[] = {dbcusid, fname, lname, phone, email};
            model.addRow(tbData);
        }

  
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyPressed
        // TODO add your handling code here:
        String cusidStr = id.getText().trim();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

    try {
       

        int empid = Integer.parseInt(cusidStr);

   
        PreparedStatement pst = JDBC.connectdb().prepareStatement(
            "SELECT * FROM customer WHERE cid= ?");
        pst.setInt(1, empid); // Use setInt for an integer parameter

        ResultSet rs = pst.executeQuery();

      
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

       

      
        while (rs.next()) {
            
            String fname = rs.getString("fname");
            String lname = rs.getString("lname");
            String phone = rs.getString("phone");
            String email = rs.getString("email");
            String dbcusid = Integer.toString(rs.getInt("cid")); // Convert int to String

            String tbData[] = {dbcusid, fname, lname, phone, email};
            model.addRow(tbData);
        }

  
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
    }}
    }//GEN-LAST:event_idKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dashboard a = new dashboard();
                    a.setVisible(true);
                    dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField pn;
    // End of variables declaration//GEN-END:variables
}
