/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Connection.JDBC;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Rasindu
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    JDBC JDBC;
    public Employee() {
        initComponents();
        JDBC = new JDBC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        rol = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 360, -1));
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 220, -1));
        jPanel1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 230, -1));
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 360, -1));
        jPanel1.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 360, -1));
        jPanel1.add(rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 360, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 360, -1));

        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });
        jPanel1.add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 360, -1));
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 360, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 70, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 70, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 70, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 70, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setText("EXIT");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emp.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int empid =  Integer.parseInt(id.getText());
        String empfname = fn.getText();
        String emplname = ln.getText();
        String empadd = add.getText();
        String emppn = pn.getText();
        String emprole= rol.getText();
        String empemail = email.getText();
        String empgen = gen.getText();
        String empnic = nic.getText();
        

        
        try {
            PreparedStatement pst = JDBC.connectdb().prepareStatement("INSERT INTO employee(id, fname, lname, address, phone, role, email, gender, nic) VALUES (?,?,?,?,?,?,?,?,?)");
            pst.setInt(1,empid);
            pst.setString(2,empfname);
            pst.setString(3,emplname);
            pst.setString(4,empadd);
            pst.setString(5,emppn);
            pst.setString(6,emprole);
            pst.setString(7,empemail);
            pst.setString(8,empgen);
            pst.setString(9,empnic);
            
            
            int rs = pst.executeUpdate();
            if (rs > 0) {
    JOptionPane.showMessageDialog(null, "Insert Successful.");
                id.setText("");
                fn.setText("");
                ln.setText("");
                add.setText("");
                pn.setText("");
                rol.setText("");
                email.setText("");
                gen.setText("");
                nic.setText("");
            }else{
                System.out.println(""+"Not save");
            }
              
        }catch(Exception E){
            System.out.println(""+E);
            
            E.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int empid =  Integer.parseInt(id.getText());
        String empfname = fn.getText();
        String emplname = ln.getText();
        String empadd = add.getText();
        String emppn = pn.getText();
        String emprole= rol.getText();
        String empemail = email.getText();
        String empgen = gen.getText();
        String empnic = nic.getText();
        
        try {
            PreparedStatement pst = JDBC.connectdb().prepareStatement("UPDATE employee SET fname=?, lname=?, address=?, phone=?, role=?, email=?, gender=?, nic=? WHERE id=?");
            pst.setString(1,empfname);
            pst.setString(2,emplname);
            pst.setString(3,empadd);
            pst.setString(4,emppn);
            pst.setString(5,emprole);
            pst.setString(6,empemail);
            pst.setString(7,empgen);
            pst.setString(8,empnic);
            pst.setInt(9,empid);
          
            
            int rs = pst.executeUpdate();
            if (rs > 0) {
                
    JOptionPane.showMessageDialog(null, "Update Data Successfully.");
            }else{
                System.out.println(""+"Not Updated.");
            }
              
        }catch(Exception E){
            System.out.println(""+E);
            E.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String empid = id.getText();
        try {
            PreparedStatement pst = JDBC.connectdb().prepareStatement("DELETE from employee WHERE id=?");
            pst.setString(1,empid);
            
            int rs = pst.executeUpdate();
            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Delete Data Successfully!");
            }else{
                System.out.println(""+"not save");
            }
            
        }catch (Exception e) {
            System.out.println(""+e);
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        emp_detail det = new emp_detail();
        det.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dashboard a = new dashboard();
                    a.setVisible(true);
                    dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField gen;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField rol;
    // End of variables declaration//GEN-END:variables
}
