/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Connection.JDBC;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Rasindu
 */
public class ordercus extends javax.swing.JFrame {

    /**
     * Creates new form order
     */
    public ordercus() {
        initComponents();
        
    }
    
     private float value = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        ocid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ta1 = new javax.swing.JLabel();
        result1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "Product Id", "Cart Id", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(tab);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 700, 130));

        ocid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ocidKeyPressed(evt);
            }
        });
        jPanel1.add(ocid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 290, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 100, -1));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLabel3.setText("ORDER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 200, 50));

        ta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ta1.setForeground(new java.awt.Color(255, 255, 255));
        ta1.setText("Amount :");
        jPanel1.add(ta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 140, 30));

        result1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        result1.setForeground(new java.awt.Color(255, 255, 255));
        result1.setText("0.00");
        jPanel1.add(result1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 130, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Checkout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 100, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ord.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cusStr = ocid.getText().trim();

    try {
       

        int cusid = Integer.parseInt(cusStr);

   
        PreparedStatement pst = JDBC.connectdb().prepareStatement(
            "SELECT * FROM cart WHERE cid= ?");
        pst.setInt(1, cusid); // Use setInt for an integer parameter

        ResultSet rs = pst.executeQuery();

      
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);

       

      
        while (rs.next()) {
            
            String dbcusid = Integer.toString(rs.getInt("cid")); // Convert int to String
            String dbproid = Integer.toString(rs.getInt("pid")); // Convert int to String
            String dbcartid = Integer.toString(rs.getInt("cartid")); // Convert int to String
            String dbquantity = Integer.toString(rs.getInt("quantity")); // Convert int to String
            String dbtotal = Float.toString(rs.getFloat("total")); // Convert int to String

            String tbData[] = {dbcusid, dbproid, dbcartid, dbquantity, dbtotal};
            model.addRow(tbData);
        }

  
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sum(){
        float sum = 0;
        for (int i = 0; i < tab.getRowCount(); i++){
            sum = sum + Float.parseFloat(tab.getValueAt(i,4).toString());
        }
        result1.setText(String.valueOf("Rs." +sum ));
     
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sum();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ocidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ocidKeyPressed
        // TODO add your handling code here:
        String cusStr = ocid.getText().trim();
if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
    try {
       

        int cusid = Integer.parseInt(cusStr);

   
        PreparedStatement pst = JDBC.connectdb().prepareStatement(
            "SELECT * FROM cart WHERE cid= ?");
        pst.setInt(1, cusid); // Use setInt for an integer parameter

        ResultSet rs = pst.executeQuery();

      
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        model.setRowCount(0);

       

      
        while (rs.next()) {
            
            String dbcusid = Integer.toString(rs.getInt("cid")); // Convert int to String
            String dbproid = Integer.toString(rs.getInt("pid")); // Convert int to String
            String dbcartid = Integer.toString(rs.getInt("cartid")); // Convert int to String
            String dbquantity = Integer.toString(rs.getInt("quantity")); // Convert int to String
            String dbtotal = Float.toString(rs.getFloat("total")); // Convert int to String

            String tbData[] = {dbcusid, dbproid, dbcartid, dbquantity, dbtotal};
            model.addRow(tbData);
        }

  
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage());
    }}
    }//GEN-LAST:event_ocidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ordercus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ordercus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ordercus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ordercus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ordercus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ocid;
    private javax.swing.JLabel result1;
    private javax.swing.JLabel ta1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}

