/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Connection.JDBC;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rasindu
 */
public class placeorder extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    JDBC JDBC;
    public placeorder() {
        initComponents();
        JDBC =new JDBC();
        getData();
        Cusdata();
       
    }

     private float value = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGenerateBillPrint = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ccid = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ppid = new javax.swing.JTextField();
        ppp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ppq = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ppt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerateBillPrint.setBackground(new java.awt.Color(153, 204, 255));
        btnGenerateBillPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerateBillPrint.setText("Generate Bill & Print");
        btnGenerateBillPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerateBillPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 670, 180, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer Details :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, -1, -1));
        jPanel1.add(ccid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 230, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Customer Id :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 100, -1));

        ppid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppidActionPerformed(evt);
            }
        });
        jPanel1.add(ppid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 230, -1));
        jPanel1.add(ppp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 230, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("product ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 90, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Price");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 50, -1));
        jPanel1.add(ppq, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 230, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 70, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 680, 50, -1));

        ppt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pptActionPerformed(evt);
            }
        });
        jPanel1.add(ppt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, 230, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Get Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, 130, 30));

        table.setBackground(new java.awt.Color(204, 204, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Brand", "Price", "Quantity", "Version"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 600, 170));

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Add To Cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 670, 150, 40));

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 670, 100, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cart Details :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, 140, -1));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "First name", "Last name", "Phone", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 600, 170));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product Details :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cart Id", "Product Id", "Customer Id", "Quantity", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 600, 210));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Order Details :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 140, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("PLACE ORDER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PLACE.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updatestock(int pid,int stock){
        
        try {
            PreparedStatement pst = JDBC.connectdb().prepareStatement("Update product SET quantity=? where pid=?");
            pst.setInt(1,pid);
            pst.setInt(2, stock);
            
            int rs = pst.executeUpdate();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int quan = Integer.parseInt(ppq.getText());
        float tot = quan * value;
        ppt.setText(Float.toString(tot));
        int Selectedrow = table.getSelectedRow();
        
        int productid = Integer.parseInt(table.getValueAt(Selectedrow, 0).toString());
        int quant = Integer.parseInt(table.getValueAt(Selectedrow, 4).toString());
        int newquant = quant-quan;
        
        updatestock(productid,newquant);
        
        table.setValueAt(newquant, Selectedrow, 4);
        
        

        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pptActionPerformed

    private void btnGenerateBillPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillPrintActionPerformed
        // TODO add your handling code here:
        cashior o = new cashior();
        o.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGenerateBillPrintActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int Selectedrow = table.getSelectedRow();
        ppid.setText(model.getValueAt(Selectedrow, 0).toString());
        ppp.setText(model.getValueAt(Selectedrow, 3).toString());
        String ctot = model.getValueAt(Selectedrow, 3).toString();
        value = Float.parseFloat(ctot);
       
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int pid =  Integer.parseInt(ppid.getText());
        int cid =  Integer.parseInt(ccid.getText());
        int quantity =  Integer.parseInt(ppq.getText());
        float total =  Float.parseFloat(ppt.getText());
        
        try {
            PreparedStatement pst = JDBC.connectdb().prepareStatement("INSERT INTO cart(pid, cid, quantity, total) VALUES (?,?,?,?)");
            pst.setInt(1,pid);
            pst.setInt(2,cid);
            pst.setInt(3,quantity);
            pst.setFloat(4, total);
            
            
            
            int rs = pst.executeUpdate();
            if (rs > 0) {
    JOptionPane.showMessageDialog(null, "Insert Successful.");
                ppid.setText("");
                ccid.setText("");
                ppq.setText("");
                ppt.setText("");
                
                CartData();

            }else{
                System.out.println(""+"Not save");
            }
              
        }catch(Exception E){
            System.out.println(""+E);
            
            E.printStackTrace();
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ppidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dashboard o = new dashboard();
        o.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int Selectedrow = jTable1.getSelectedRow();
        ccid.setText(model.getValueAt(Selectedrow, 0).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new placeorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateBillPrint;
    private javax.swing.JTextField ccid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField ppid;
    private javax.swing.JTextField ppp;
    private javax.swing.JTextField ppq;
    private javax.swing.JTextField ppt;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
public void getData(){
    
    try {
        PreparedStatement pst = JDBC.connectdb().prepareStatement("SELECT pid, pname, brand, price, quantity, version from product");
        
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            
            int ProductId = rs.getInt("pid");
            String productname = rs.getString("pname");
            String productbrand = rs.getString("brand");
            Float productprice = rs.getFloat("price");
            String productquantity = rs.getString("quantity");
            String productversion = rs.getString("version");
            Float newprice = productprice * 1.1f;
            
            String Pidstr = Integer.toString(ProductId);
            String pprice = Float.toString(newprice);
            

            String tbData[] = {Pidstr, productname, productbrand, pprice, productquantity,productversion};
            DefaultTableModel model = (DefaultTableModel)table.getModel();
            model.addRow(tbData);
        }

    } catch (Exception e) {
        e.printStackTrace();
        
    }
}

public void Cusdata(){
    
    try {
        PreparedStatement pst = JDBC.connectdb().prepareStatement("SELECT cid, fname, lname, phone, email from customer");
        
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            
            int cusId = rs.getInt("cid");
            String cusfn = rs.getString("fname");
            String cusln = rs.getString("lname");
            String cusphone = rs.getString("phone");
            String cusemail = rs.getString("email");
            
            String Cidstr = Integer.toString(cusId);
            

            String tbData[] = {Cidstr, cusfn, cusln, cusphone, cusemail};
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.addRow(tbData);
        }

    } catch (Exception e) {
        e.printStackTrace();
        
    }
}
public void CartData(){
    
    try {
        PreparedStatement pst = JDBC.connectdb().prepareStatement("SELECT cartid, pid, cid, quantity, total from cart");
        
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            
            int cId = rs.getInt("cartid");
            int pId = rs.getInt("pid");
            int cusId = rs.getInt("cid");
            int quan = rs.getInt("quantity");
            Float Total = rs.getFloat("total");
            
            String Cartidstr = Integer.toString(cId);
            String Pidstr = Integer.toString(pId);
            String Cidstr = Integer.toString(cusId);
            String Quanstr = Integer.toString(quan);
            String Totalstr = Float.toString(Total);
            

            String tbData[] = {Cartidstr, Pidstr, Cidstr, Quanstr, Totalstr};
            DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
            model.addRow(tbData);
        }

    } catch (Exception e) {
        e.printStackTrace();
        
    }
}
}
